import type { DefinicaoFerramentaIa } from "../tipos";
import {
  CAMPOS_FILTRO_ANALITICO,
  NOMES_DIMENSAO_ANALITICA,
  NOMES_METRICA_ANALITICA,
  OPERADORES_FILTRO_ANALITICO,
} from "../analitico/tipos";
import { consultarAnaliticoIa } from "../analitico/consultar";
import { consultarDadosIa } from "../consulta/consultar";
import { catalogoCompactoConsultaIa } from "../consulta/compacto";
import { SCHEMA_CONSULTAR_DADOS_IA } from "../consulta/schema-ferramenta";
import {
  analisarGruposFiscaisProdutosIa,
  analisarOperacaoFiscalIa,
  classificarProdutoFiscalMotorIa,
  consultarCestIa,
  consultarClassificacaoIbsCbsIa,
  consultarNcmIa,
  consultarOrigemMercadoriaIa,
  pesquisarNcmIa,
  recomendarGrupoFiscalIa,
  sugerirCestIa,
  validarFiscalProdutoMotorIa,
  validarNcmIa,
} from "../fiscal/motor-tools";
import {
  consultarCaixaAtualIa,
  consultarCaixaIa,
  consultarMovimentosCaixaIa,
  consultarResumoCaixaIa,
  consultarStatusCaixaIa,
} from "./caixa";
import {
  buscarClientesIa,
  consultarCarteiraClienteIa,
  consultarCarteiraIa,
  consultarClienteIa,
  consultarClientesEmAbertoIa,
  consultarCreditosClienteIa,
  consultarRecebimentosIa,
} from "./clientes";
import {
  consultarConfiguracaoFiscalIa,
  consultarDocumentoFiscalIa,
  consultarEmissaoFiscalIa,
  consultarNotasFiscaisIa,
  consultarStatusNfceIa,
  consultarStatusNfeIa,
  diagnosticarNotaIa,
} from "./fiscal";
import {
  objetoSchema,
  SCHEMA_PERIODO_IA,
  type FerramentaRegistradaIa,
} from "./definicao";
import {
  abrirCaixaIa,
  abrirCarteiraIa,
  abrirClientesIa,
  abrirConfiguracoesIa,
  abrirFiscalIa,
  abrirPdvIa,
  abrirProdutosIa,
  abrirVendaIa,
  abrirVendasIa,
  iniciarNfceIa,
  iniciarNfeIa,
  novoClienteIa,
  novoProdutoIa,
} from "./navegar";
import { consultarNotificacoesIa } from "./notificacoes";
import {
  buscarProdutosIa,
  consultarEstoqueBaixoIa,
  consultarEstoqueIa,
  consultarEstoqueNegativoIa,
  consultarProdutoIa,
} from "./produtos";
import {
  consultarFormasPagamentoIa,
  consultarProdutosMaisVendidosIa,
  consultarTotalVendidoIa,
  consultarVendaIa,
  consultarVendasIa,
  rankingProdutosIa,
  resumirVendasPeriodoIa,
} from "./vendas";

const periodo = SCHEMA_PERIODO_IA;

export const FERRAMENTAS_SUBSTITUIDAS_POR_CONSULTAR_DADOS = [
  "buscar_produtos",
  "consultar_produto",
  "consultar_estoque",
  "consultar_estoque_baixo",
  "consultar_estoque_negativo",
  "buscar_clientes",
  "consultar_cliente",
  "consultar_carteira",
  "consultar_carteira_cliente",
  "consultar_clientes_em_aberto",
  "consultar_recebimentos",
  "consultar_creditos_cliente",
  "consultar_vendas",
  "consultar_venda",
  "consultar_total_vendido",
  "consultar_formas_pagamento",
  "consultar_produtos_mais_vendidos",
  "resumir_vendas_periodo",
  "ranking_produtos",
  "consultar_caixa",
  "consultar_status_caixa",
  "consultar_caixa_atual",
  "consultar_movimentos_caixa",
  "consultar_resumo_caixa",
  "consultar_documento_fiscal",
  "consultar_notas_fiscais",
  "consultar_status_nfe",
  "consultar_status_nfce",
  "consultar_emissao_fiscal",
  "consultar_notificacoes",
  "consultar_analitico",
] as const;

function semArgs(
  handler: (ctx: Parameters<FerramentaRegistradaIa["handler"]>[0]) => ReturnType<
    FerramentaRegistradaIa["handler"]
  >
): FerramentaRegistradaIa["handler"] {
  return (ctx) => handler(ctx);
}

export const CATALOGO_FERRAMENTAS_IA: FerramentaRegistradaIa[] = [
  {
    name: "consultar_dados",
    description: [
      "Consulta estruturada somente leitura da empresa ativa.",
      catalogoCompactoConsultaIa(),
      "Nunca envie SQL, empresa_id, SELECT * ou nomes de tabela interna.",
      "Para faturamento use vendas/vendas_itens com status finalizada e campos snapshot (total, preco_unitario), não preco_venda cadastral.",
      "Se a consulta for inválida, corrija a especificação. Máximo 2 correções.",
    ].join("\n"),
    schema: SCHEMA_CONSULTAR_DADOS_IA,
    category: "consulta",
    mode: "read",
    availableOnFree: false,
    requiredPermission: null,
    handler: consultarDadosIa,
  },
  {
    name: "buscar_produtos",
    description:
      "Busca produtos da empresa ativa por nome, código, EAN, categoria ou marca. Se houver vários, peça para o usuário escolher. Não altera cadastro.",
    schema: objetoSchema({
      busca: { type: "string" },
      descricao: { type: "string" },
      nome: { type: "string" },
      codigo: { type: "string" },
      ean: { type: "string" },
      categoria: { type: "string" },
      marca: { type: "string" },
      ativo: { type: "boolean" },
    }),
    category: "produtos",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "produtos", acao: "acessar" },
    handler: buscarProdutosIa,
  },
  {
    name: "consultar_produto",
    description: "Consulta um produto da empresa ativa por id ou busca. Em caso de ambiguidade, não escolha sozinho.",
    schema: objetoSchema({
      produtoId: { type: "string" },
      busca: { type: "string" },
    }),
    category: "produtos",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "produtos", acao: "acessar" },
    handler: consultarProdutoIa,
  },
  {
    name: "consultar_estoque",
    description: "Consulta estoque da empresa ativa. filtro: acabando, zerados, negativos.",
    schema: objetoSchema({
      filtro: { type: "string", description: "acabando, zerados, negativos" },
    }),
    category: "estoque",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "estoque", acao: "acessar" },
    handler: consultarEstoqueIa,
  },
  {
    name: "consultar_estoque_baixo",
    description: "Lista produtos com estoque baixo, zerado ou negativo da empresa ativa.",
    schema: objetoSchema({}),
    category: "estoque",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "estoque", acao: "acessar" },
    handler: consultarEstoqueBaixoIa,
  },
  {
    name: "consultar_estoque_negativo",
    description: "Lista produtos com estoque negativo da empresa ativa.",
    schema: objetoSchema({}),
    category: "estoque",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "estoque", acao: "acessar" },
    handler: consultarEstoqueNegativoIa,
  },
  {
    name: "buscar_clientes",
    description:
      "Busca clientes da empresa ativa por nome ou CPF/CNPJ. Se houver vários João, peça para escolher. Não cadastra cliente.",
    schema: objetoSchema({
      busca: { type: "string" },
      nome: { type: "string" },
      clienteId: { type: "string" },
    }),
    category: "clientes",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar" },
    handler: buscarClientesIa,
  },
  {
    name: "consultar_cliente",
    description: "Consulta cliente da empresa ativa. Em ambiguidade, não escolha sozinho.",
    schema: objetoSchema({
      clienteId: { type: "string" },
      busca: { type: "string" },
    }),
    category: "clientes",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar" },
    handler: consultarClienteIa,
  },
  {
    name: "consultar_carteira",
    description: "Consulta débitos, créditos e vencidos da carteira da empresa ativa. Não recebe nem baixa.",
    schema: objetoSchema({
      clienteId: { type: "string" },
      somenteVencidos: { type: "boolean" },
      ordenar: { type: "string", description: "aberto ou vencido" },
    }),
    category: "carteira",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar_carteira" },
    handler: consultarCarteiraIa,
  },
  {
    name: "consultar_carteira_cliente",
    description: "Consulta a carteira de um cliente específico da empresa ativa.",
    schema: objetoSchema({ clienteId: { type: "string" } }),
    category: "carteira",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar_carteira" },
    handler: consultarCarteiraClienteIa,
  },
  {
    name: "consultar_clientes_em_aberto",
    description: "Lista clientes com saldo em aberto na carteira da empresa ativa.",
    schema: objetoSchema({}),
    category: "carteira",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar_carteira" },
    handler: consultarClientesEmAbertoIa,
  },
  {
    name: "consultar_recebimentos",
    description: "Lista recebimentos recentes da carteira de um cliente. Não executa recebimento.",
    schema: objetoSchema({ clienteId: { type: "string" } }),
    category: "carteira",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar_carteira" },
    handler: consultarRecebimentosIa,
  },
  {
    name: "consultar_creditos_cliente",
    description: "Consulta créditos disponíveis do cliente na empresa ativa.",
    schema: objetoSchema({ clienteId: { type: "string" } }),
    category: "carteira",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar_carteira" },
    handler: consultarCreditosClienteIa,
  },
  {
    name: "consultar_vendas",
    description: "Resumo de vendas do período da empresa ativa. Datas naturais são convertidas no servidor.",
    schema: objetoSchema({
      periodo,
      vendaId: { type: "string" },
      clienteId: { type: "string" },
      rankingClientes: { type: "boolean" },
    }),
    category: "vendas",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: consultarVendasIa,
  },
  {
    name: "consultar_venda",
    description: "Consulta uma venda da empresa ativa por id ou número. Não cancela nem altera.",
    schema: objetoSchema({
      vendaId: { type: "string" },
      numero: { type: "string" },
    }),
    category: "vendas",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: consultarVendaIa,
  },
  {
    name: "consultar_total_vendido",
    description: "Total vendido, quantidade e ticket médio do período na empresa ativa.",
    schema: objetoSchema({ periodo, clienteId: { type: "string" } }),
    category: "vendas",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: consultarTotalVendidoIa,
  },
  {
    name: "consultar_formas_pagamento",
    description: "Formas de pagamento usadas nas vendas do período.",
    schema: objetoSchema({ periodo }),
    category: "vendas",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: consultarFormasPagamentoIa,
  },
  {
    name: "consultar_produtos_mais_vendidos",
    description: "Ranking dos produtos mais vendidos no período.",
    schema: objetoSchema({ periodo }),
    category: "vendas",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: consultarProdutosMaisVendidosIa,
  },
  {
    name: "resumir_vendas_periodo",
    description: "Resume faturamento e pode comparar com o período anterior.",
    schema: objetoSchema({ periodo, compararAnterior: { type: "boolean" } }),
    category: "vendas",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: resumirVendasPeriodoIa,
  },
  {
    name: "ranking_produtos",
    description: "Ranking dos produtos mais vendidos no período.",
    schema: objetoSchema({ periodo }),
    category: "vendas",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: rankingProdutosIa,
  },
  {
    name: "consultar_caixa",
    description: "Consulta status, saldo e movimentos do caixa da empresa ativa. Não abre, fecha, faz sangria nem suprimento.",
    schema: objetoSchema({}),
    category: "caixa",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "caixa", acao: "acessar" },
    handler: semArgs(consultarCaixaIa),
  },
  {
    name: "consultar_status_caixa",
    description: "Informa se o caixa da empresa ativa está aberto ou fechado.",
    schema: objetoSchema({}),
    category: "caixa",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "caixa", acao: "acessar" },
    handler: semArgs(consultarStatusCaixaIa),
  },
  {
    name: "consultar_caixa_atual",
    description: "Consulta o caixa atual da empresa ativa.",
    schema: objetoSchema({}),
    category: "caixa",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "caixa", acao: "acessar" },
    handler: semArgs(consultarCaixaAtualIa),
  },
  {
    name: "consultar_movimentos_caixa",
    description: "Lista movimentos recentes do caixa atual. Não cria movimento.",
    schema: objetoSchema({}),
    category: "caixa",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "caixa", acao: "acessar" },
    handler: semArgs(consultarMovimentosCaixaIa),
  },
  {
    name: "consultar_resumo_caixa",
    description: "Resumo de entradas, saídas e saldo do caixa atual.",
    schema: objetoSchema({}),
    category: "caixa",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "caixa", acao: "acessar" },
    handler: semArgs(consultarResumoCaixaIa),
  },
  {
    name: "consultar_configuracao_fiscal",
    description:
      "Consulta configuração fiscal pública da empresa ativa (CRT, UF, séries). Nunca retorna senha, CSC, certificado ou API keys.",
    schema: objetoSchema({}),
    category: "fiscal",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: semArgs(consultarConfiguracaoFiscalIa),
  },
  {
    name: "consultar_documento_fiscal",
    description: "Consulta status de um documento fiscal. Não emite, cancela nem retransmite.",
    schema: objetoSchema({
      emissaoId: { type: "string" },
      vendaId: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarDocumentoFiscalIa,
  },
  {
    name: "consultar_notas_fiscais",
    description: "Lista notas fiscais recentes da empresa ativa. Não emite documento.",
    schema: objetoSchema({
      status: { type: "string" },
      modelo: { type: "string", description: "55 NF-e ou 65 NFC-e" },
      emissaoId: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarNotasFiscaisIa,
  },
  {
    name: "consultar_status_nfe",
    description: "Consulta status das NF-e da empresa ativa.",
    schema: objetoSchema({ status: { type: "string" }, emissaoId: { type: "string" } }),
    category: "fiscal",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarStatusNfeIa,
  },
  {
    name: "consultar_status_nfce",
    description: "Consulta status das NFC-e da empresa ativa.",
    schema: objetoSchema({ status: { type: "string" }, emissaoId: { type: "string" } }),
    category: "fiscal",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarStatusNfceIa,
  },
  {
    name: "consultar_emissao_fiscal",
    description: "Lista notas rejeitadas ou aguardando reconciliação.",
    schema: objetoSchema({
      status: { type: "string" },
      emissaoId: { type: "string" },
      modelo: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarEmissaoFiscalIa,
  },
  {
    name: "diagnosticar_nota",
    description: "Explica o status/motivo de um documento fiscal. Não retransmite.",
    schema: objetoSchema({
      emissaoId: { type: "string" },
      vendaId: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: diagnosticarNotaIa,
  },
  {
    name: "consultar_notificacoes",
    description: "Resume avisos ativos da Central de Notificações da empresa.",
    schema: objetoSchema({}),
    category: "notificacoes",
    mode: "read",
    availableOnFree: true,
    requiredPermission: null,
    handler: semArgs(consultarNotificacoesIa),
  },
  {
    name: "pesquisar_ncm",
    description: "Pesquisa NCM vigente na base oficial local. Não inventa código.",
    schema: objetoSchema({
      termos: { type: "string" },
      descricao: { type: "string" },
      dataReferencia: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: pesquisarNcmIa,
  },
  {
    name: "consultar_ncm",
    description: "Consulta um NCM específico na base oficial vigente.",
    schema: objetoSchema({ codigo: { type: "string" }, dataReferencia: { type: "string" } }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarNcmIa,
  },
  {
    name: "validar_ncm",
    description: "Valida se o NCM existe e está vigente.",
    schema: objetoSchema({ codigo: { type: "string" }, dataReferencia: { type: "string" } }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: validarNcmIa,
  },
  {
    name: "sugerir_cest",
    description: "Sugere CEST a partir do NCM. CEST não implica ST.",
    schema: objetoSchema({
      ncm: { type: "string" },
      descricao: { type: "string" },
      dataReferencia: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: sugerirCestIa,
  },
  {
    name: "consultar_cest",
    description: "Consulta/valida CEST na base oficial. Não assume ST.",
    schema: objetoSchema({
      codigo: { type: "string" },
      cest: { type: "string" },
      ncm: { type: "string" },
      dataReferencia: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarCestIa,
  },
  {
    name: "consultar_origem_mercadoria",
    description: "Explica códigos de origem. Não infere origem pela marca.",
    schema: objetoSchema({
      origemAtual: { type: "string" },
      origemInformada: { type: "string" },
      marca: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarOrigemMercadoriaIa,
  },
  {
    name: "consultar_classificacao_ibs_cbs",
    description: "Valida CST IBS/CBS e cClassTrib oficiais do produto/grupo.",
    schema: objetoSchema({
      produtoId: { type: "string" },
      dataReferencia: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: consultarClassificacaoIbsCbsIa,
  },
  {
    name: "classificar_produto_fiscal",
    description:
      "Analisa classificação fiscal do produto com a base oficial. Somente leitura: não grava cadastro nem auditoria.",
    schema: objetoSchema({
      produtoId: { type: "string" },
      descricao: { type: "string" },
      descricaoComplementar: { type: "string" },
      marca: { type: "string" },
      categoria: { type: "string" },
      material: { type: "string" },
      composicao: { type: "string" },
      finalidade: { type: "string" },
      uso: { type: "string" },
      caracteristicasTecnicas: { type: "string" },
      origemInformadaUsuario: { type: "string" },
      dataReferencia: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: classificarProdutoFiscalMotorIa,
  },
  {
    name: "validar_fiscal_produto",
    description: "Compara o fiscal atual do produto com a base oficial vigente.",
    schema: objetoSchema({
      produtoId: { type: "string" },
      dataReferencia: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: validarFiscalProdutoMotorIa,
  },
  {
    name: "analisar_operacao_fiscal",
    description: "Analisa a tributação de uma operação. Não emite documento.",
    schema: objetoSchema({
      produtoId: { type: "string" },
      tipoOperacao: { type: "string" },
      ufDestino: { type: "string" },
      destinatarioId: { type: "string" },
      contribuinteIcms: { type: "boolean" },
      consumidorFinal: { type: "boolean" },
      dataReferencia: { type: "string" },
      origemInformadaUsuario: { type: "string" },
    }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: analisarOperacaoFiscalIa,
  },
  {
    name: "recomendar_grupo_fiscal",
    description: "Recomenda grupo fiscal existente só da empresa ativa. Não atribui.",
    schema: objetoSchema({ produtoId: { type: "string" } }),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: recomendarGrupoFiscalIa,
  },
  {
    name: "analisar_grupos_fiscais_produtos",
    description: "Análise em lote somente leitura: revisão fiscal, NCM extinto, grupos sem IBS/CBS.",
    schema: objetoSchema({}),
    category: "fiscal",
    mode: "read",
    availableOnFree: false,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: semArgs(analisarGruposFiscaisProdutosIa),
  },
  {
    name: "consultar_analitico",
    description:
      "Consulta analítica da empresa ativa. Envie só métricas, dimensões e filtros do schema. O backend calcula. Não envie SQL, tabela, empresa_id nem join.",
    schema: objetoSchema(
      {
        metricas: {
          type: "array",
          items: { type: "string", enum: [...NOMES_METRICA_ANALITICA] },
        },
        dimensoes: {
          type: "array",
          items: { type: "string", enum: [...NOMES_DIMENSAO_ANALITICA] },
        },
        filtros: {
          type: "array",
          items: objetoSchema(
            {
              campo: { type: "string", enum: [...CAMPOS_FILTRO_ANALITICO] },
              operador: { type: "string", enum: [...OPERADORES_FILTRO_ANALITICO] },
              valor: { type: ["string", "number", "boolean", "array"] },
            },
            ["campo", "operador", "valor"]
          ),
        },
        periodo,
        de: { type: "string", description: "YYYY-MM-DD" },
        ate: { type: "string", description: "YYYY-MM-DD" },
        comparacao: { type: "boolean" },
        ordenacao: objetoSchema({
          metrica: { type: "string", enum: [...NOMES_METRICA_ANALITICA] },
          direcao: { type: "string", enum: ["asc", "desc"] },
        }),
        limite: { type: "number" },
        reutilizarContexto: { type: "boolean" },
      },
      ["metricas"]
    ),
    category: "analitico",
    mode: "read",
    availableOnFree: false,
    requiredPermission: null,
    handler: consultarAnaliticoIa,
  },
  {
    name: "abrir_pdv",
    description: "Navega para o PDV. Não inicia venda nem altera estoque.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "pdv", acao: "acessar" },
    handler: semArgs(abrirPdvIa),
  },
  {
    name: "abrir_produtos",
    description: "Navega para a lista de produtos.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "produtos", acao: "acessar" },
    handler: semArgs(abrirProdutosIa),
  },
  {
    name: "novo_produto",
    description: "Abre a tela oficial de novo produto. Não grava produto.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "produtos", acao: "acessar" },
    handler: semArgs(novoProdutoIa),
  },
  {
    name: "abrir_clientes",
    description: "Navega para a lista de clientes.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar" },
    handler: semArgs(abrirClientesIa),
  },
  {
    name: "novo_cliente",
    description: "Abre a tela oficial de novo cliente. Não cadastra.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar" },
    handler: semArgs(novoClienteIa),
  },
  {
    name: "abrir_vendas",
    description: "Navega para a lista de vendas.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: semArgs(abrirVendasIa),
  },
  {
    name: "abrir_venda",
    description: "Abre uma venda existente para o usuário. Não cancela nem altera.",
    schema: objetoSchema({ vendaId: { type: "string" } }),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "vendas", acao: "acessar" },
    handler: abrirVendaIa,
  },
  {
    name: "abrir_caixa",
    description: "Abre a tela de Caixa. Não abre/fecha sessão, não faz sangria nem suprimento.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "caixa", acao: "acessar" },
    handler: semArgs(abrirCaixaIa),
  },
  {
    name: "abrir_carteira",
    description: "Abre a Carteira. Não recebe, não baixa, não estorna.",
    schema: objetoSchema({ clienteId: { type: "string" } }),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "clientes", acao: "acessar_carteira" },
    handler: abrirCarteiraIa,
  },
  {
    name: "abrir_fiscal",
    description: "Abre o módulo Fiscal. Não emite documento.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: semArgs(abrirFiscalIa),
  },
  {
    name: "iniciar_nfe",
    description: "Abre o fluxo oficial de NF-e. Não emite, não transmite, não escolhe tributação.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: semArgs(iniciarNfeIa),
  },
  {
    name: "iniciar_nfce",
    description: "Abre o PDV para o fluxo de NFC-e. Não emite nem transmite.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "pdv", acao: "acessar" },
    handler: semArgs(iniciarNfceIa),
  },
  {
    name: "abrir_configuracoes",
    description: "Abre configurações fiscais. Não altera configuração.",
    schema: objetoSchema({}),
    category: "navegacao",
    mode: "navigate",
    availableOnFree: true,
    requiredPermission: { recurso: "fiscal", acao: "acessar" },
    handler: semArgs(abrirConfiguracoesIa),
  },
];

export const MAPA_FERRAMENTAS_IA = new Map(
  CATALOGO_FERRAMENTAS_IA.map((item) => [item.name, item])
);

export function definicoesFerramentasParaModelo(): DefinicaoFerramentaIa[] {
  const ocultas = new Set<string>(FERRAMENTAS_SUBSTITUIDAS_POR_CONSULTAR_DADOS);
  return CATALOGO_FERRAMENTAS_IA.filter((item) => !ocultas.has(item.name)).map((item) => ({
    nome: item.name,
    descricao: item.description,
    parametros: item.schema,
  }));
}

export function ferramentaDoCatalogo(nome: string) {
  return MAPA_FERRAMENTAS_IA.get(nome as FerramentaRegistradaIa["name"]) ?? null;
}
