export type ResultadoIsolamento = "PASS" | "P0" | "P1" | "P2";

export type LinhaMatriz = {
  modulo: string;
  operacao: string;
  aParaA: "OK" | "N/A";
  aParaB: "BLOQUEADO" | "VAZA" | "INCOMPLETO";
  bParaA: "BLOQUEADO" | "VAZA" | "INCOMPLETO";
  protecao: string;
  resultado: ResultadoIsolamento;
};

export const MATRIZ_ISOLAMENTO: LinhaMatriz[] = [
  {
    modulo: "Empresa ativa",
    operacao: "resolverEmpresaAtiva",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "helper principal+ativo",
    resultado: "PASS",
  },
  {
    modulo: "Clientes",
    operacao: "SELECT/UPDATE/DELETE",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "RLS tem_acesso_empresa + assert backend",
    resultado: "PASS",
  },
  {
    modulo: "Produtos",
    operacao: "SELECT/editar/excluir/usar na venda",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "RLS + RPC p.empresa_id",
    resultado: "PASS",
  },
  {
    modulo: "Produtos",
    operacao: "código 100 em A e B",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "UNIQUE (empresa_id, codigo)",
    resultado: "PASS",
  },
  {
    modulo: "Categorias/marcas/grupos",
    operacao: "cadastro RPC",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "RPC mesma empresa",
    resultado: "PASS",
  },
  {
    modulo: "Grupos fiscais",
    operacao: "produto.grupo_fiscal_id direto",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "FK composta (grupo_fiscal_id, empresa_id) versionada",
    resultado: "PASS",
  },
  {
    modulo: "Vendas",
    operacao: "GET/editar/cancelar",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "RLS + API empresa_id",
    resultado: "PASS",
  },
  {
    modulo: "Itens da venda",
    operacao: "Venda A + Produto/Cliente B",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "RPC + assert backend",
    resultado: "PASS",
  },
  {
    modulo: "Estoque",
    operacao: "consultar/movimentar/estornar",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "RLS + RPC tem_acesso_empresa; internos revogados",
    resultado: "PASS",
  },
  {
    modulo: "Carteira",
    operacao: "consultar/débito/recalcular/baixar",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "RPC cliente.empresa_id; *_interno revogado",
    resultado: "PASS",
  },
  {
    modulo: "PIX",
    operacao: "integração/cobrança/cancelar/confirmar",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "resolverEmpresaPix + carregarCobrancaDaEmpresa",
    resultado: "PASS",
  },
  {
    modulo: "Fiscal",
    operacao: "GET emissão/reconciliar/cancelar/CC-e/inutilizar",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "API id + empresa_id",
    resultado: "PASS",
  },
  {
    modulo: "Fiscal",
    operacao: "XML/DANFE inflight",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "chave empresaId+emissaoId+tipo",
    resultado: "PASS",
  },
  {
    modulo: "Fiscal",
    operacao: "fuso horário empresas_fiscal",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "empresa ativa + eq empresa_id; sem herança entre tenants",
    resultado: "PASS",
  },
  {
    modulo: "Numeração",
    operacao: "55/homologação/série 1 coexistir",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "UNIQUE (empresa_id, modelo, ambiente, serie)",
    resultado: "PASS",
  },
  {
    modulo: "Catálogo",
    operacao: "slug e pedido",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "RPC pelo slug; sem empresa_id do browser",
    resultado: "PASS",
  },
  {
    modulo: "Pedidos online",
    operacao: "converter em venda",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "eq empresa_id da sessão",
    resultado: "PASS",
  },
  {
    modulo: "Usuários/admin",
    operacao: "listar/editar/senha/remover",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "vínculo na empresa ativa",
    resultado: "PASS",
  },
  {
    modulo: "Fiscal",
    operacao: "diagnóstico Geranet/SEFAZ",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "obterContextoAdministracaoUsuarios + empresa da sessão",
    resultado: "PASS",
  },
  {
    modulo: "RPCs internas",
    operacao: "EXECUTE authenticated",
    aParaA: "N/A",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "REVOKE FASE 1B",
    resultado: "PASS",
  },
  {
    modulo: "Cron fiscal",
    operacao: "reconciliar/contingência",
    aParaA: "OK",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "item.empresa_id do registro",
    resultado: "PASS",
  },
  {
    modulo: "IDOR mensagens",
    operacao: "UUID PIX/usuários em API",
    aParaA: "N/A",
    aParaB: "BLOQUEADO",
    bParaA: "BLOQUEADO",
    protecao: "404 Recurso não encontrado",
    resultado: "PASS",
  },
  {
    modulo: "Integridade residual",
    operacao: "venda.natureza_id e grupo_fiscal_id FK simples",
    aParaA: "OK",
    aParaB: "INCOMPLETO",
    bParaA: "INCOMPLETO",
    protecao: "sem FK composta nesta fase; próximo item",
    resultado: "P2",
  },
];
