import type { DefinicaoMetricaAnalitica, NomeMetricaAnalitica } from "./tipos";

export const REGISTRO_METRICAS_ANALITICAS: Record<
  NomeMetricaAnalitica,
  DefinicaoMetricaAnalitica
> = {
  faturamento: {
    nome: "faturamento",
    dominio: "vendas",
    tipo: "moeda",
    fonte: "vendas.valor_total / vendas_itens.valor_total",
    formula: "Soma do valor das vendas válidas no período (por produto, soma dos itens).",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca", "cliente", "vendedor", "forma_pagamento", "tempo"],
  },
  quantidade_vendas: {
    nome: "quantidade_vendas",
    dominio: "vendas",
    tipo: "contagem",
    fonte: "vendas.id",
    formula: "Quantidade de vendas válidas (status de faturamento). Por produto: vendas distintas com o item.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca", "cliente", "vendedor", "forma_pagamento", "tempo"],
  },
  quantidade_vendida: {
    nome: "quantidade_vendida",
    dominio: "vendas",
    tipo: "quantidade",
    fonte: "vendas_itens.quantidade",
    formula: "Soma das quantidades dos itens em vendas válidas.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca", "cliente", "vendedor", "tempo"],
  },
  ticket_medio: {
    nome: "ticket_medio",
    dominio: "vendas",
    tipo: "moeda",
    fonte: "faturamento / quantidade_vendas",
    formula: "faturamento ÷ quantidade_vendas. Zero se não houver vendas.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca", "cliente", "vendedor", "forma_pagamento", "tempo"],
    derivada: true,
  },
  desconto: {
    nome: "desconto",
    dominio: "vendas",
    tipo: "moeda",
    fonte: "vendas.desconto",
    formula: "Soma dos descontos das vendas válidas. Não rateia por produto.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "cliente", "vendedor", "forma_pagamento", "tempo"],
  },
  custo_vendido: {
    nome: "custo_vendido",
    dominio: "vendas",
    tipo: "moeda",
    fonte: "vendas_itens.quantidade × produtos.preco_custo",
    formula: "Quantidade vendida × custo cadastrado atual do produto. Não é custo histórico da venda.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca", "cliente", "tempo"],
    aviso: "Custo de cadastro atual, não o custo no momento da venda.",
  },
  margem_bruta: {
    nome: "margem_bruta",
    dominio: "vendas",
    tipo: "moeda",
    fonte: "faturamento dos itens − custo_vendido",
    formula: "faturamento_itens − custo_vendido. Não é lucro líquido (sem despesas, impostos operacionais nem CMV histórico).",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca", "cliente", "tempo"],
    derivada: true,
    aviso: "Margem bruta potencial sobre o custo cadastrado. Não chamar de lucro.",
  },
  margem_percentual: {
    nome: "margem_percentual",
    dominio: "vendas",
    tipo: "percentual",
    fonte: "margem_bruta / faturamento",
    formula: "(margem_bruta ÷ faturamento) × 100. Nulo se faturamento = 0.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca", "cliente", "tempo"],
    derivada: true,
    aviso: "Percentual da margem bruta potencial, não lucro.",
  },
  estoque_atual: {
    nome: "estoque_atual",
    dominio: "estoque",
    tipo: "quantidade",
    fonte: "estoque_atual.quantidade",
    formula: "Saldo atual. Posição do momento, não série histórica.",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
  },
  estoque_minimo: {
    nome: "estoque_minimo",
    dominio: "estoque",
    tipo: "quantidade",
    fonte: "estoque_atual.estoque_minimo",
    formula: "Mínimo cadastrado na posição atual.",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
  },
  valor_estoque_custo: {
    nome: "valor_estoque_custo",
    dominio: "estoque",
    tipo: "moeda",
    fonte: "estoque_atual.quantidade × produtos.preco_custo",
    formula: "quantidade × custo cadastrado.",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
  },
  valor_estoque_venda: {
    nome: "valor_estoque_venda",
    dominio: "estoque",
    tipo: "moeda",
    fonte: "estoque_atual.quantidade × produtos.preco_venda",
    formula: "quantidade × preço de venda cadastrado (potencial, não faturamento).",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
  },
  quantidade_produtos: {
    nome: "quantidade_produtos",
    dominio: "estoque",
    tipo: "contagem",
    fonte: "produtos.id",
    formula: "Quantidade de produtos ativos considerados após filtros.",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
  },
  produtos_zerados: {
    nome: "produtos_zerados",
    dominio: "estoque",
    tipo: "contagem",
    fonte: "situacaoEstoque = sem",
    formula: "Contagem de produtos com quantidade = 0 (regra oficial situacaoEstoque).",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
  },
  produtos_negativos: {
    nome: "produtos_negativos",
    dominio: "estoque",
    tipo: "contagem",
    fonte: "situacaoEstoque = negativo",
    formula: "Contagem de produtos com quantidade < 0.",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
  },
  produtos_abaixo_minimo: {
    nome: "produtos_abaixo_minimo",
    dominio: "estoque",
    tipo: "contagem",
    fonte: "situacaoEstoque = baixo",
    formula: "Contagem com quantidade > 0 e ≤ estoque_minimo (regra oficial).",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
  },
  saldo_aberto: {
    nome: "saldo_aberto",
    dominio: "carteira",
    tipo: "moeda",
    fonte: "situacaoCarteiraCliente.debitoAberto",
    formula: "Soma do débito em aberto da regra oficial da Carteira. Posição atual.",
    recurso: "clientes",
    acao: "acessar_carteira",
    graos: ["empresa", "cliente"],
  },
  saldo_vencido: {
    nome: "saldo_vencido",
    dominio: "carteira",
    tipo: "moeda",
    fonte: "situacaoCarteiraCliente.vencido",
    formula: "Soma do vencido da regra oficial da Carteira. Posição atual.",
    recurso: "clientes",
    acao: "acessar_carteira",
    graos: ["empresa", "cliente"],
  },
  recebimentos: {
    nome: "recebimentos",
    dominio: "carteira",
    tipo: "moeda",
    fonte: "carteira_cliente_recebimentos.valor",
    formula: "Soma dos recebimentos da carteira no período.",
    recurso: "clientes",
    acao: "acessar_carteira",
    graos: ["empresa", "cliente", "tempo"],
  },
  quantidade_devedores: {
    nome: "quantidade_devedores",
    dominio: "carteira",
    tipo: "contagem",
    fonte: "clientes com debitoAberto > 0",
    formula: "Quantidade de clientes com saldo em aberto > 0.",
    recurso: "clientes",
    acao: "acessar_carteira",
    graos: ["empresa", "cliente"],
  },
  quantidade_compras: {
    nome: "quantidade_compras",
    dominio: "vendas",
    tipo: "contagem",
    fonte: "vendas.id por cliente",
    formula: "Quantidade de vendas válidas do cliente no período.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "cliente"],
  },
  valor_comprado: {
    nome: "valor_comprado",
    dominio: "vendas",
    tipo: "moeda",
    fonte: "vendas.valor_total",
    formula: "Soma do faturamento do cliente no período.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "cliente"],
  },
  ticket_cliente: {
    nome: "ticket_cliente",
    dominio: "vendas",
    tipo: "moeda",
    fonte: "valor_comprado / quantidade_compras",
    formula: "valor_comprado ÷ quantidade_compras.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "cliente"],
    derivada: true,
  },
  ultima_compra: {
    nome: "ultima_compra",
    dominio: "vendas",
    tipo: "data",
    fonte: "vendas.finalizada_at",
    formula: "Data da venda válida mais recente no período carregado (epoch ms para ordenação).",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "cliente"],
  },
  entradas: {
    nome: "entradas",
    dominio: "caixa",
    tipo: "moeda",
    fonte: "totaisDoLivro.entradas",
    formula: "Entradas do caixa aberto atual.",
    recurso: "caixa",
    acao: "acessar",
    graos: ["empresa"],
  },
  saidas: {
    nome: "saidas",
    dominio: "caixa",
    tipo: "moeda",
    fonte: "totaisDoLivro.saidas",
    formula: "Saídas do caixa aberto atual.",
    recurso: "caixa",
    acao: "acessar",
    graos: ["empresa"],
  },
  saldo_esperado: {
    nome: "saldo_esperado",
    dominio: "caixa",
    tipo: "moeda",
    fonte: "totaisDoLivro.saldoAtual",
    formula: "Saldo esperado do caixa aberto. Pode vir nulo em fechamento cego.",
    recurso: "caixa",
    acao: "acessar",
    graos: ["empresa"],
  },
  giro_estoque: {
    nome: "giro_estoque",
    dominio: "estoque",
    tipo: "quantidade",
    fonte: "quantidade_vendida / estoque_atual",
    formula: "quantidade_vendida no período ÷ estoque_atual. Nulo se estoque ≤ 0.",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
    derivada: true,
  },
  cobertura_estoque_dias: {
    nome: "cobertura_estoque_dias",
    dominio: "estoque",
    tipo: "dias",
    fonte: "estoque_atual / (quantidade_vendida / dias_periodo)",
    formula: "estoque_atual ÷ média diária vendida no período. Nulo se não houver venda.",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
    derivada: true,
  },
  valor_imobilizado: {
    nome: "valor_imobilizado",
    dominio: "estoque",
    tipo: "moeda",
    fonte: "valor_estoque_custo",
    formula: "Igual a valor_estoque_custo (dinheiro parado em estoque a custo de cadastro).",
    recurso: "estoque",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca"],
    derivada: true,
  },
  participacao_no_faturamento: {
    nome: "participacao_no_faturamento",
    dominio: "vendas",
    tipo: "percentual",
    fonte: "faturamento_linha / faturamento_total",
    formula: "(faturamento da linha ÷ faturamento do conjunto filtrado) × 100.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["produto", "categoria", "marca", "cliente", "vendedor", "forma_pagamento", "tempo"],
    derivada: true,
  },
  crescimento_periodo: {
    nome: "crescimento_periodo",
    dominio: "vendas",
    tipo: "percentual",
    fonte: "comparação de faturamento",
    formula: "((faturamento_atual − faturamento_anterior) ÷ faturamento_anterior) × 100. Exige comparacao.",
    recurso: "vendas",
    acao: "acessar",
    graos: ["empresa", "produto", "categoria", "marca", "cliente", "vendedor", "forma_pagamento", "tempo"],
    derivada: true,
  },
  inadimplencia_cliente: {
    nome: "inadimplencia_cliente",
    dominio: "carteira",
    tipo: "percentual",
    fonte: "saldo_vencido / saldo_aberto",
    formula: "(saldo_vencido ÷ saldo_aberto) × 100. Nulo se aberto = 0.",
    recurso: "clientes",
    acao: "acessar_carteira",
    graos: ["empresa", "cliente"],
    derivada: true,
  },
  produtos_revisao_fiscal: {
    nome: "produtos_revisao_fiscal",
    dominio: "fiscal",
    tipo: "contagem",
    fonte: "analisarGruposFiscaisProdutos.quantidadeRevisao",
    formula: "Quantidade de produtos ativos que o Motor Fiscal marcou para revisão. Não classifica NCM.",
    recurso: "fiscal",
    acao: "acessar",
    graos: ["empresa"],
  },
  grupos_fiscais_incompativeis: {
    nome: "grupos_fiscais_incompativeis",
    dominio: "fiscal",
    tipo: "contagem",
    fonte: "analisarGruposFiscaisProdutos.gruposIncompativeis",
    formula: "Quantidade de produtos com grupo fiscal incompatível na análise em lote.",
    recurso: "fiscal",
    acao: "acessar",
    graos: ["empresa"],
  },
  notas_rejeitadas: {
    nome: "notas_rejeitadas",
    dominio: "fiscal",
    tipo: "contagem",
    fonte: "fiscal_emissoes.status = rejeitada",
    formula: "Quantidade de emissões rejeitadas da empresa (até o limite da consulta).",
    recurso: "fiscal",
    acao: "acessar",
    graos: ["empresa"],
  },
};

export function metricaAnalitica(nome: string): DefinicaoMetricaAnalitica | null {
  return Object.prototype.hasOwnProperty.call(REGISTRO_METRICAS_ANALITICAS, nome)
    ? REGISTRO_METRICAS_ANALITICAS[nome as NomeMetricaAnalitica]
    : null;
}
